## Preprocesssing
In this stage we do a first quickly look for :
- Delimit dataset to use according with the scope of analysis
- Data quality validation

In [ ]:
import pandas as pd
df = pd.read_csv("../data/raw/England CSV.csv")
df2 = pd.read_csv("../data/raw/England 2 CSV.csv")

In [ ]:
df.head(5)

,Date,Season,HomeTeam,AwayTeam,FTH Goals,FTA Goals,FT Result,HTH Goals,HTA Goals,HT Result,...,H Fouls,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,Display_Order,League
0,16/01/2025,2024/25,Ipswich Town,Brighton & Hove Albion,0,2,A,0.0,1.0,A,...,13.0,14.0,1.0,9.0,2.0,2.0,0.0,0.0,20250116,Premier League
1,16/01/2025,2024/25,Man United,Southampton,3,1,H,0.0,1.0,A,...,7.0,10.0,4.0,4.0,1.0,3.0,0.0,0.0,20250116,Premier League
2,15/01/2025,2024/25,Everton,Aston Villa,0,1,A,0.0,0.0,D,...,17.0,10.0,8.0,5.0,2.0,1.0,0.0,0.0,20250115,Premier League
3,15/01/2025,2024/25,Leicester,Crystal Palace,0,2,A,0.0,0.0,D,...,7.0,6.0,4.0,3.0,0.0,0.0,0.0,0.0,20250115,Premier League
4,15/01/2025,2024/25,Newcastle,Wolves,3,0,H,1.0,0.0,H,...,10.0,13.0,4.0,2.0,0.0,2.0,0.0,0.0,20250115,Premier League

In [20]:
df2.head(5)

,Date,Season,HomeTeam,AwayTeam,FTH Goals,FTA Goals,FT Result,HTH Goals,HTA Goals,HT Result,...,H Fouls,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,Display_Order,League
0,15/01/2025,2024/25,Blackburn,Portsmouth,3,0,H,0.0,0.0,D,...,15.0,19.0,5.0,6.0,1.0,3.0,0.0,0.0,20250115,English Second
1,14/01/2025,2024/25,Cardiff,Watford,1,1,D,0.0,0.0,D,...,8.0,14.0,7.0,3.0,1.0,2.0,0.0,0.0,20250114,English Second
2,14/01/2025,2024/25,Plymouth,Oxford,1,1,D,0.0,1.0,A,...,8.0,10.0,6.0,3.0,1.0,1.0,0.0,0.0,20250114,English Second
3,6/01/2025,2024/25,QPR,Luton,2,1,H,1.0,1.0,D,...,10.0,9.0,3.0,4.0,1.0,1.0,0.0,0.0,20250106,English Second
4,5/01/2025,2024/25,Sunderland,Portsmouth,1,0,H,1.0,0.0,H,...,9.0,10.0,7.0,3.0,1.0,2.0,0.0,1.0,20250105,English Second

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12153 entries, 0 to 12152
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           12153 non-null  object
 1   Season         12153 non-null  object
 2   HomeTeam       12153 non-null  object
 3   AwayTeam       12153 non-null  object
 4   FTH Goals      12153 non-null  int64
 5   FTA Goals      12153 non-null  int64
 6   FT Result      12153 non-null  object
 7   HTH Goals      11229 non-null  float64
 8   HTA Goals      11229 non-null  float64
 9   HT Result      11229 non-null  object
 10  Referee        9329 non-null   object
 11  H Shots        9329 non-null   float64
 12  A Shots        9329 non-null   float64
 13  H SOT          9329 non-null   float64
 14  A SOT          9329 non-null   float64
 15  H Fouls        9329 non-null   float64
 16  A Fouls        9329 non-null   float64
 17  H Corners      9329 non-null   float64
 18  A Corners      9329 non-null   float64
 19  H Yellow       9329 non-null   float64
 20  A Yellow       9329 non-null   float64
 21  H Red          9329 non-null   float64
 22  A Red          9329 non-null   float64
 23  Display_Order  12153 non-null  int64
 24  League         12153 non-null  object
dtypes: float64(14), int64(3), object(8)
memory usage: 2.3+ MB

In [13]:
print(df['Date'].min())

1/01/1994

In [22]:
print(df['Date'].max())

9/12/2024

In [38]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df[df['Season'] == "2023/24"]['Date'].max()

Timestamp('2024-05-19 00:00:00')

In [41]:
df[df['Season'] == "2013/14"]['Date'].min()

Timestamp('2013-08-17 00:00:00')

In [42]:
lu = df[df['Season'] == "2023/24"]['Date'].max()
ll = df[df['Season'] == "2013/14"]['Date'].min()

datasetPremier = df[(df['Date'] >= ll) & (df['Date'] <= lu)]

In [46]:
datasetPremier.to_csv(r'C:\Users\camilo.alvarez\Documents\TrainingDE\PremierLeague\data\raw\datasetPremier.csv')

## Summary -- Scope Analaysis

In this ocassion I'll only focus in first league of England Soccer (Premier League) even though in the source we can access data for first and second league (df and df2).
In addition the data set collects information since 1994 however for this project the sample space will be limited for the last 10 years, that is, from 2014 to 2024. For this reason the new dataset **_datasetPremier_** had built under the before mentioned conditions.

In rencently years the Premier League has become in probably the most intersting professional soccer league in the world and this project seek find intersting facts realated that.

Objectives of the project: 

### Insights : 
- Which teams have been the most consistent in their performance over the last 10 years?
- Which teams have the most comebacks (wins after trailing)?
- How does playing at home or away affect the results?

### Visualizations :
- A simple dashboard for teams performance

### Models: 
- Pronostic of goals in the current season